config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"

Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :posts, only: [:create, :destroy, :edit, :update, :show] do
    resource :spam, only: [:create, :destroy]
  end

  resources :categories, only: [:new, :create, :index]
  resources :locations, only: [:new, :create, :index]
  resource :search, only: [:show]

  constraints Monban::Constraints::SignedIn.new do
    root "users#show", as: :home
  end

  constraints Monban::Constraints::SignedOut.new do
    root "sessions#new"
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :location
  has_many :spams

  validates :content, presence: true
end

app/models/spam.rb
class Spam < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts

  has_many :spams
  has_many :spammed_posts, through: :spams, source: :post

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  def spam_post(post)
    spammed_posts.append(post)
  end

  def unspam_post(post)
    spammed_posts.delete post
  end

  def has_spam(post)
    spammed_posts.include? post
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :back
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to locations_path
    else
      render :back
    end
  end

  private

  def location_params
    params.require(:location).permit(:name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    post = current_user.posts.build(post_params)

    if post.save
      redirect_to current_user
    else
      redirect_to :back
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.delete

    redirect_to :back
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to current_user
    else
      render :back
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(
    :content,
    :title,
    :location_id,
    :category_id,
    :url
    )
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @posts = Post.where(filters)
  end

  private

  def search_params
    params.permit(:location_id, :category_id)
  end

  def filters
    search_params.slice(:location_id, :category_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/spams_controller.rb
class SpamsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    current_user.spam_post(post)

    redirect_to :back
  end

  def destroy
    post = Post.find(params[:post_id])
    current_user.unspam_post(post)

    redirect_to :back
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def show
    @posts = current_user.posts.page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<h1>What would you like to find?</h1>

<ul>
  <% @categories.each do |category| %>
    <li><%= category.name %></li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h3>Add a Category to Craigstr: </h3>
<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Craigstr</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="session" >
    <% if signed_in? %>
      <%= link_to "Sign out", session_path, method: :delete %>
      <p class="inline"> You're signed in as <%= current_user.email %> </p>
    <% else %>
      <%= link_to "Sign in", new_session_path %>
      <%= link_to "Sign up", new_user_path %>
    <% end %>
  </div>

  <div class="admin">
    <% if signed_in? && current_user.is_admin %>
      <%= link_to "Add a New Location", new_location_path %>
      <%= link_to "Add a Category", new_category_path %>
    <% end %>
  </div>

  <div class="search">

    <p>Quick Search:</p>

    <%= form_tag search_path, method: :get do %>
      <%= select_tag "location_id", options_from_collection_for_select(Location.all,"id", "name") %>
      <%= select_tag "category_id", options_from_collection_for_select(Category.all, "id", "name") %>
      <%= submit_tag "Search" %>
    <% end %>

  </div>

<%= yield %>

</body>
</html>

app/views/locations/index.html.erb
<h1>Where would you like to go?</h1>

<ul>
  <% @locations.each do |location| %>
    <li><%= location.name %></li>
  <% end %>
</ul>

app/views/locations/new.html.erb
<h3>Add a Location to Craigstr: </h3>
<%= form_for @location do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/posts/_form.html.erb
<fieldset>
  <%= form_for post do |form| %>

    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>

    <div>
      <%= form.collection_select :location_id, Location.all, :id, :name, prompt: true %>
    </div>

    <div>
      <%= form.collection_select :category_id, Category.all, :id, :name, prompt: true %>
    </div>

    <div>
      <%= form.label :url, "Image url: " %>
      <%= form.text_field :url %>
    </div>

    <div>
      <%= form.submit "Post" %>
    </div>

  <% end %>
</fieldset>

app/views/posts/_post.html.erb
<fieldset>

  <b><%= link_to post.title, post_path(post) %></b>
  <br>
  <%= post.content %>
  <br>
  <p>Category: <%= post.category.name %> Posted in: <%= post.location.name %></p>

  <% if post.user_id == current_user.id || current_user.is_admin %>
    <div>
      <%= button_to "Delete!", post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  <% end %>

  <div>
    <%= button_to "Edit", edit_post_path(post), method: :get %>
  </div>

  <div>
    <%= image_tag post.url, width:"500" %>
    <p>posted by <%= post.user.email %></p>
  </div>
  <div>
    <% if current_user.has_spam(post) %>
      <%= button_to "UnSpam", post_spam_path(post), method: :delete %>
    <% else %>
      <%= button_to "Spam", post_spam_path(post) %>
    <% end %>
  </div>
</fieldset>

app/views/posts/edit.html.erb
<h1>Edit</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<%= render @post %>

app/views/searches/show.html.erb
<h1> Results </h1>

<% @posts.each do |post| %>
  <%= link_to post.title, post_path(post) %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.email.capitalize %></h1>

<%= render "posts/form", post: Post.new %>

<%= render @posts %>

<%= paginate @posts, window: 5 %>